import { useState } from 'react'
import type { Post } from '@socialscience/shared'
import { usePublishPost, useDeletePost, useUpdatePost } from '../../hooks/use-posts'
import { useUIStore } from '../../stores/ui.store'

const STATUS_COLORS: Record<string, string> = {
  draft: 'var(--muted-foreground)',
  queued: 'var(--secondary)',
  scheduled: 'var(--accent)',
  published: 'var(--primary)',
  failed: 'var(--destructive)',
}

interface PostCardProps {
  post: Post
  showAccount?: boolean
}

export function PostCard({ post }: PostCardProps) {
  const [editing, setEditing] = useState(false)
  const [content, setContent] = useState(post.content)
  const { mutateAsync: publish, isPending: publishing } = usePublishPost()
  const { mutateAsync: deletePost } = useDeletePost()
  const { mutateAsync: update, isPending: saving } = useUpdatePost()
  const addToast = useUIStore((s) => s.addToast)

  const statusColor = STATUS_COLORS[post.status] ?? 'var(--muted-foreground)'

  async function handlePublish() {
    try {
      await publish(post.id)
      addToast({ title: 'QUEST COMPLETE!', description: 'Post published successfully.', type: 'success' })
    } catch (err) {
      addToast({ title: 'PUBLISH FAILED', description: (err as Error).message, type: 'error' })
    }
  }

  async function handleSaveEdit() {
    await update({ id: post.id, content })
    setEditing(false)
  }

  return (
    <div className="card-pixel p-4 space-y-3">
      {/* Status bar */}
      <div className="flex items-center justify-between">
        <span
          className="font-pixel text-[7px] px-2 py-1 pixel-border"
          style={{ color: `hsl(${statusColor})`, borderColor: `hsl(${statusColor})` }}
        >
          {post.status.toUpperCase()}
        </span>
        <span className="text-xs text-[hsl(var(--muted-foreground))]">
          {post.scheduledFor
            ? `⏰ ${new Date(post.scheduledFor).toLocaleString()}`
            : post.publishedAt
            ? `✓ ${new Date(post.publishedAt).toLocaleString()}`
            : new Date(post.createdAt).toLocaleString()}
        </span>
      </div>

      {/* Content */}
      {editing ? (
        <textarea
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="w-full pixel-border bg-[hsl(var(--input))] p-2 text-sm resize-none outline-none focus:border-[hsl(var(--primary))] min-h-[80px]"
          maxLength={300}
        />
      ) : (
        <p className="text-base leading-relaxed">{post.content}</p>
      )}

      {post.llmProvider && (
        <div className="text-[10px] text-[hsl(var(--muted-foreground))]">
          ✦ Generated by {post.llmProvider} / {post.llmModel}
        </div>
      )}

      {post.errorMessage && (
        <div className="text-xs text-[hsl(var(--destructive))] pixel-border border-[hsl(var(--destructive))] p-2">
          {post.errorMessage}
        </div>
      )}

      {/* Actions */}
      {post.status !== 'published' && (
        <div className="flex gap-2 flex-wrap">
          {editing ? (
            <>
              <button
                onClick={handleSaveEdit}
                disabled={saving}
                className="btn-pixel px-3 py-1 text-xs bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"
              >
                SAVE
              </button>
              <button onClick={() => { setEditing(false); setContent(post.content) }} className="btn-pixel px-3 py-1 text-xs">
                CANCEL
              </button>
            </>
          ) : (
            <>
              {(post.status === 'draft' || post.status === 'queued') && (
                <button
                  onClick={handlePublish}
                  disabled={publishing}
                  className="btn-pixel px-3 py-1 text-xs bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]"
                >
                  {publishing ? 'POSTING...' : 'PUBLISH NOW'}
                </button>
              )}
              <button onClick={() => setEditing(true)} className="btn-pixel px-3 py-1 text-xs">
                EDIT
              </button>
              <button
                onClick={() => deletePost(post.id)}
                className="btn-pixel px-3 py-1 text-xs text-[hsl(var(--destructive))]"
              >
                DELETE
              </button>
            </>
          )}
        </div>
      )}
    </div>
  )
}
